# Generated by Django 4.1.5 on 2023-04-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_pic', models.FileField(upload_to='images')),
                ('bedroom', models.CharField(max_length=100)),
                ('washroom', models.CharField(max_length=100)),
                ('square_feet', models.CharField(max_length=100)),
                ('Property_location', models.CharField(max_length=100)),
                ('Property_price', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
            ],
        ),
    ]
